# Generated by Django 5.1.1 on 2024-10-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в обработке', 'В обработке'), ('доставлен', 'Доставлен'), ('отменен', 'Отменен')], default='в обработке', max_length=20),
        ),
    ]
