# Generated by Django 5.1.1 on 2024-10-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в обработке', 'В обработке'), ('доставлен', 'Доставлен'), ('отменен', 'Отменен')], default='pending', max_length=20),
        ),
    ]
